name: WS Flow Bot

on:
  schedule:
    - cron: "*/5 * * * *"   # запуск каждые 5 минут
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    timeout-minutes: 5   # важно: Actions не может работать бесконечно

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install websockets aiohttp

      - name: Run WS bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
